#!/usr/bin/env bash

which docker &>/dev/null || {
    echo "Error: docker isn't installed"
    exit 1
}
which realpath &>/dev/null || {
    echo "Error: realpath isn't installed. Install coreutils with homebrew."
    exit 1
}

cd pi-gen
for i in ./config*; do
    if [ $i = ./config ]; then
        ./build-docker.sh && touch stage2/SKIP_IMAGES stage0/SKIP stage1/SKIP stage2/SKIP
    else
        ./build-docker.sh -c $i
    fi
done

