#!/usr/bin/env bash

which docker &>/dev/null || {
    echo "Error: docker isn't installed"
    exit 1
}
which realpath &>/dev/null || {
    echo "Error: realpath isn't installed. Install coreutils with homebrew."
    exit 1
}

cd "$(dirname "$BASH_SOURCE")"

cp copy_in/config pi-gen/config
target_wpa_supp=pi-gen/stage2/02-net-tweaks/files/wpa_supplicant.conf
if [ ! -f "$target_wpa_supp" ]; then
    echo "Error: $target_wpa_supp was missing! Did pi-gen move it?"
fi
cp copy_in/wpa_supplicant.conf "$target_wpa_supp"

cd pi-gen

rm -f stage2/EXPORT_NOOBS
touch stage3/SKIP stage4/SKIP stage5/SKIP
touch stage4/SKIP_IMAGES stage5/SKIP_IMAGES

if [ -f ./config ]; then
    ./build-docker.sh || {
        echo "Failed to build on ./config"
        exit 1
    }
    touch stage2/SKIP_IMAGES stage0/SKIP stage1/SKIP stage2/SKIP
fi

# idk what this was doing...
# for i in ./config*; do
#     if [ "$i" != ./config ]; then
#         ./build-docker.sh -c $i
#     fi
# done
