#!/usr/bin/env bash

git submodule init
git submodule update
rm -rf pi-gen/config*
for i in stage*; do
    rm -rf pi-gen/$i
done
cp -r config* stage* pi-gen 2>/dev/null

cd pi-gen
rm -f stage2/EXPORT_NOOBS
touch stage3/SKIP stage4/SKIP stage5/SKIP
touch stage4/SKIP_IMAGES stage5/SKIP_IMAGES
